using System.Text.Json;
using System.Text.Json.Serialization;
using Engine.Core;
using Google.Protobuf.Reflection;

namespace Client.Tests.Conformance;

internal sealed record SchemaHashCase
{
    [JsonPropertyName("logicalName")]
    public required string LogicalName { get; init; }

    [JsonPropertyName("schemaHash")]
    public required string SchemaHash { get; init; }

    [JsonPropertyName("canonical")]
    public required string Canonical { get; init; }
}

internal sealed record SchemaHashVectors
{
    [JsonPropertyName("version")]
    public required int Version { get; init; }

    [JsonPropertyName("algorithm")]
    public required string Algorithm { get; init; }

    [JsonPropertyName("cases")]
    public required IReadOnlyList<SchemaHashCase> Cases { get; init; }
}

/// <summary>
/// Pins the SDK's schema hash implementation.
/// </summary>
/// <remarks>
/// The SDK and the coordinator share no code, so this is not a duplicate of the
/// coordinator's suite — it is the second half of the check. If the SDK computed a
/// different hash from the world it talks to, every component type it declared would be
/// refused, and the only thing that catches that before runtime is this file and
/// <c>protocol/conformance/schema-hash.json</c>.
///
/// The vectors are generated by the coordinator's suite
/// (<c>ECS_WRITE_CONFORMANCE_VECTORS=1</c>); this side only ever reads them.
/// </remarks>
public class SchemaHashConformanceTests
{
    private static readonly MessageDescriptor[] Cases =
    [
        Testing.V1.ConformanceLeaf.Descriptor,
        Testing.V1.ConformanceLeafTwin.Descriptor,
        Testing.V1.ConformanceMaps.Descriptor,
        Testing.V1.ConformancePresence.Descriptor,
        Testing.V1.ConformanceOneof.Descriptor,
        Testing.V1.ConformanceEnums.Descriptor,
        Testing.V1.ConformanceRecursive.Descriptor,
        Testing.V1.ConformanceWellKnown.Descriptor,
        Testing.V1.ConformanceScalars.Descriptor,
        Testing.V1.ConformanceOrdering.Descriptor,
        Ecs.V1.ComponentInfo.Descriptor,
        Ecs.V1.ComponentSchema.Descriptor,
        Ecs.V1.ParentRef.Descriptor,
        Movement.V1.Position.Descriptor,
        Ecs.Protocol.V1.ComponentBatch.Descriptor,
        Ecs.Protocol.V1.StructuralCommand.Descriptor,
    ];

    private static SchemaHashVectors Load()
    {
        var options = new JsonSerializerOptions
        {
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        };

        return JsonSerializer.Deserialize<SchemaHashVectors>(File.ReadAllText(VectorPath), options)
            ?? throw new InvalidOperationException("Vector file is empty.");
    }

    [Fact]
    public void EveryCoveredTypeIsPinned()
    {
        var pinned = Load().Cases.Select(c => c.LogicalName).ToHashSet(StringComparer.Ordinal);

        foreach (var descriptor in Cases)
            Assert.Contains(descriptor.FullName, pinned);
    }

    [Fact]
    public void CanonicalFormMatchesTheVectors()
    {
        foreach (var vector in Load().Cases)
        {
            var descriptor = Cases.Single(d => d.FullName == vector.LogicalName);

            // Compared before the hash: a rendering diff says which line is wrong.
            Assert.Equal(vector.Canonical, SchemaHash.Canonicalize(descriptor));
        }
    }

    [Fact]
    public void HashMatchesTheVectors()
    {
        foreach (var vector in Load().Cases)
        {
            var descriptor = Cases.Single(d => d.FullName == vector.LogicalName);

            Assert.Equal(vector.SchemaHash, $"0x{SchemaHash.Of(descriptor):x16}");
        }
    }

    [Fact]
    public void ComponentTypeExposesTheSameHashItWillDeclare()
    {
        // ComponentType<T> is what the handshake actually sends, so it has to agree with
        // the vectors too, not merely with SchemaHash.
        Assert.Equal(
            $"0x{ComponentType<Movement.V1.Position>.SchemaHash:x16}",
            Load().Cases.Single(c => c.LogicalName == "movement.v1.Position").SchemaHash);
    }

    private static string VectorPath
    {
        get
        {
            var directory = new DirectoryInfo(AppContext.BaseDirectory);
            while (directory is not null)
            {
                var candidate = Path.Combine(
                    directory.FullName, "protocol", "conformance", "schema-hash.json");

                if (File.Exists(candidate)) return candidate;
                directory = directory.Parent;
            }

            throw new InvalidOperationException("Could not locate the conformance vectors.");
        }
    }
}
